### ISSUE TITLE
Safe produce with function parameter

### ISSUE THREAD

**Issue by asjir** [giusepperaso/structura.js#111]
Hi thank you very much for the library.

I wanted to raise an issue which is not really with the library, but with typescript, yet I encountered it using it and got a workaround for myself, so decided to share it in case it could help some users or in case it could be adjusted for in the library.

The problem is that if I write `const myVal = ((f: () => void) => f())(() => 3)` Ts will happily assign type `void` to `myVal`.

So here's what it looks like when I tried to curry `safeProduceWithPatches`:

```typescript
const f =
  <T>(x: T) =>
  (f: (x: UnFreeze<T>) => void) =>
    safeProduceWithPatches(x, f)
f(s)((s) => (s.hey = "hi")) // no TS error
```
So I lose the safety. Notice that here I thought I'd only limit f to be the non-returning forms. If I write instead: `(f: (x: UnFreeze<T>) => void | T)` then it works fine again and produces the correct error on the last line.
Going in this direction `(f: (x: UnFreeze<T>) => void | undefined)` also produces the error correctly and accomplishes what I intended.

**Comment by giusepperaso** [comment]
Yes, in typescript a function with a return type of void basically means "ignore the return type because we will not use it"

So the fact that it does not throw errors is by design

You probably don't even need to put `void | ` before the return type, so you can just write `(f: (x: UnFreeze<T>) =>  undefined)` or `(f: (x: UnFreeze<T>) => T)` depending on your needs
