### ISSUE TITLE
Problem with circular data

### ISSUE THREAD

**Issue by yanislavgalyov** [giusepperaso/structura.js#112]
The following code:
```
import { produce } from "structurajs";

class HbNode {
  constructor(data, parent) {
    this.parent = parent;
    this.children = [];
    Object.assign(this, data);
  }
  addChild(data, index) {
    const child = new HbNode(data, this);
    this.children.splice(index, 0, child);
  }
}

const root = new HbNode(
  {
    id: "0",
    name: "root",
  },
);

const children = [
  {
    id: "1",
    name: "child1",
  },
  {
    id: "2",
    name: "child2",
  },
];

const rootDraft = produce(root, (draft) => {
  for (const [i, value] of children.entries()) {
    draft.addChild(value, i);
  }
});

console.log(JSON.stringify(rootDraft, null, 4));
```
will throw 
```
file:///D:/tmp/structure-test/node_modules/structurajs/dist/index.js:552
    return Reflect.ownKeys(i);
                   ^

RangeError: Maximum call stack size exceeded
    at Reflect.ownKeys (<anonymous>)
    at ne.ownKeys (file:///D:/tmp/structure-test/node_modules/structurajs/dist/index.js:552:20)
    at Reflect.ownKeys (<anonymous>)
    at ne.ownKeys (file:///D:/tmp/structure-test/node_modules/structurajs/dist/index.js:552:20)
    at Reflect.ownKeys (<anonymous>)
    at ne.ownKeys (file:///D:/tmp/structure-test/node_modules/structurajs/dist/index.js:552:20)
    at Reflect.ownKeys (<anonymous>)
    at ne.ownKeys (file:///D:/tmp/structure-test/node_modules/structurajs/dist/index.js:552:20)
    at Reflect.ownKeys (<anonymous>)
    at ne.ownKeys (file:///D:/tmp/structure-test/node_modules/structurajs/dist/index.js:552:20)
```
due to circular data structure. Is `structurejs` intended to support this kind of circular data?

**Comment by giusepperaso** [comment]
Hi @yanislavgalyov 

there are two problems, but they are not strictly related to circular references

the first problem, as pointed out in [this part of the docs](https://giusepperaso.github.io/structura.js/gotchas.html#potential-dangling-proxy-references-if-you-assign-unproxied-objects-into-the-draft), is that you could end up with a proxy still inside the result object if you assign a portion of the draft to a non-draft object

structura does not handle this automatically for you (because it would be computationally expensive) but you can solve it quite easily

```javascript
import { produce, target } from "structurajs";

class HbNode {
  constructor(data, parent) {
    this.parent = target(parent); // <-- use target here
    this.children = [];
    Object.assign(this, data);
  }
// rest of the code -->
```

note that the function _target()_ will do nothing if you use your data structure outside of a produce function, so you can use it safely

The second problem, but this has nothing to do with the library, is that you are trying to use JSON.stringify with a circular reference object. This is not supported in browsers. If you want to do this, use a json library that supports circular objects like [flatted](https://github.com/WebReflection/flatted)

**Comment by yanislavgalyov** [comment]
Hi @giusepperaso 

> the first problem, as pointed out in [this part of the docs](https://giusepperaso.github.io/structura.js/gotchas.html#potential-dangling-proxy-references-if-you-assign-unproxied-objects-into-the-draft), is that you could end up with a proxy still inside the result object if you assign a portion of the draft to a non-draft object

Thanks for pointing out, I read the docs but I guess didn't understand all of it. Anyway, thank you very much!
