### ISSUE TITLE
Does castDraft in immer library exist in this library?

### ISSUE THREAD

**Issue by araera111** [giusepperaso/structura.js#80]
```TypeScript
type Todo = {readonly done: boolean}

type State = {
    readonly finishedTodos: readonly Todo[]
    readonly unfinishedTodos: readonly Todo[]
}

function markAllFinished(state: State) {
    produce(state, draft => {
        draft.finishedTodos = state.unfinishedTodos // => The type 'readonly Todo[]' is 'readonly' and cannot be assigned to the mutable type '{ done: boolean; }[]'
    })
}
```

in Immer
draft.finishedTodos = castDraft(state.unfinishedTodos) // => will make the error disappear.

This library is very interesting in that it improves the immer speed problem.

**Comment by giusepperaso** [comment]
Hi @araera111, I'm glad you like it!

The first option would be to read from the draft itself because this is already mutable, however reading from a proxy is slightly slower

Another option is to use the helper type [UnFreeze](https://giusepperaso.github.io/structura.js/freezing.html#unfreezing), it is normally used to unfreeze the result from a producer but it's also useful in this case:

```typescript
function markAllFinished(state: State) {
  produce(state, (draft) => {
    const casted = state as UnFreeze<State> 
    draft.finishedTodos = casted.unfinishedTodos;
  });
}
```

I've also just released a new version which has a new utility called *unfreeze*, which is a bit less verbose

```typescript
function markAllFinished(state: State) {
  produce(state, (draft) => {
    draft.finishedTodos = unfreeze(state).unfinishedTodos;
  });
}
```

**Comment by araera111** [comment]
Thanks for the update. It is working very well in my use case.
